apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-oracle-app
  labels:
    app: the-oracle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-oracle-app
  template:
    metadata:
      labels:
        app: the-oracle-app
    spec:
      containers:
        - name: graphql-engine
          image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080         
          command:
            - graphql-engine
            - --database-url
            - "postgres://$(POSTGRES_DB_USER):$(POSTGRES_DB_PASSWORD)@$(POSTGRES_DB_HOST)/postgres"
            - serve
          env:
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_DEV_MODE
              value: "false"
            - name: POSTGRES_DB_HOST
              value: 127.0.0.1:5432
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-credentials
                  key: password
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              value: "anonymous"
            - name: HASURA_GRAPHQL_CORS_DOMAIN
              value: "http://localhost:4200, https://tchief.github.io"
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=the-oracle-app:europe-west3:the-oracle-app-hasura=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
